### ISSUE TITLE
Abbreviations Filter error, Windows 10, release 5.0.931

### ISSUE THREAD

**Issue by cokelly** [Juris-M/jurism-abbreviations#3] opened 2020-11-02 10:28 UTC
I hope I've diagnosed this properly and put it in the right place.

Juris-M throws an error on Windows 10 for its latest release (5.0.93m1).

Having updated, two windows open. One says:

```
XML Parsing Error: undefined entity
Location: chrome://zotero/content/standalone/standalone.xul
Line Number 44, Column 1:<window id="main-window"
^
```

The other:

```
NetworkError: A network error occurred.
    getContentsFromURL@chrome://zotero/content/xpcom/file.js:339:5
    Zotero.Intl</this.init@chrome://zotero/content/xpcom/intl.js:81:23
    this.init<@chrome://zotero/content/xpcom/zotero.js:249:5
From previous event:
    ZoteroService@file:///C:/Program%20Files%20(x86)/Juris-M%20Standalone/components/zotero-service.js:377:7
    initializePlugin<@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Program%20Files%20(x86)/Juris-M%20Standalone/extensions/abbrevs-filter@juris-m.github.io/bootstrap.js:56:14
    observe@resource://gre/modules/addons/XPIProvider.jsm -> file:///C:/Program%20Files%20(x86)/Juris-M%20Standalone/extensions/abbrevs-filter@juris-m.github.io/bootstrap.js:241:3
```

The same error occurs whether I try to update directly from 5.0.90 or whether I do a clean install (having uninstalled and removed both APPDATA folders). I've tried this on two Windows PCs (all I have to hand I'm afraid, OS-wise) and the same errors recur in both.

**Comment by fbennett** [comment] 2020-11-02 12:40
Thanks for reporting this! It looks like a string is missing from the locale. Checking now on a local Windows instance...

**Comment by fbennett** [comment] 2020-11-02 13:04
Okay, I've reproduced the error here. There is a missing string in non-US locale that crashes the client. There isn't a way to reset the locale after the crash, but happily the crash window gives you an "Update" button. I'll get this fixed now, push an update, and post back soon. Then you'll be able to update to 5.0.93m2, and get back on the road.

**Comment by fbennett** [comment] 2020-11-02 13:28
Checked the source code, and there was nothing subtle about this one. The en-GB locale for the UK was entirely missing for some reason. I must have mis-keyed at some point while preparing the upgrade. There is another important UK-related fix that I have been preparing for this release, so I'll polish that off now, and push a release soon. Please stand by ...

**Comment by cokelly** [comment] 2020-11-02 13:31
Works as planned, including the update path. Thanks for the quick fix!

**Comment by fbennett** [comment] 2020-11-02 14:34
The Windows 5.0.93m2 release is up. You should be able to use the Update button after a crash to pull it in.

**Closed as completed** 2020-11-02 14:33 UTC

**Comment by fbennett** [comment] 2020-11-02 14:35
Welcome back! :-)
